config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  get 'intro/index'
  get 'intro/show'
  devise_for :users
  
  resources :lists # /list/index 
  get "users/:id/index", to: "users#index", as: :home #user/index => page that shows all lists
  get "users/:id", to: "users#show", as: :user # user/show
  
  # for fufillment
  patch "/list/:id/assign", to: "lists#assign", as: :assign_list
  patch "/list/:id/complete", to: "lists#complete", as: :complete_list

  # for admin actions
  patch "/users/:id/role", to: "users#updateRole"
  
 resources :types
  
  root 'intro#index'

end

app/models/list.rb
class List < ApplicationRecord
  attr_accessor :travel_distance, :travel_time
  geocoded_by :address
  after_validation :geocode

  validates :address, :presence => true,
  :length => { :minimum => 10 }
  validates :pickUpDate, :presence => true

  validate :timeslot_cannot_be_in_the_past

  validate :pickupdate_cannot_be_in_the_past

  belongs_to :user
  has_many :types
  accepts_nested_attributes_for :types

  def pickupdate_cannot_be_in_the_past
    if pickUpDate.present? && pickUpDate < Date.today
      errors.add(:pickUpDate, "can't be in the past")
    end
  end  

  def timeslot_cannot_be_in_the_past
    if pickUpDate.present? && pickUpDate == Date.today && timeslot.present? && timeslot.utc.strftime( "%H%M%S%N" ) < Time.now.utc.strftime( "%H%M%S%N" )
      errors.add(:timeslot, "#{Time.now} #{timeslot}" )
    end
  end 

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  def index
    @lists = List.all
  end

  def new
    @list = List.new
    type = @list.types.build
  end

  def create 
    @list = List.new(list_params)
    @list.status = 0
    @list.user = current_user

    if @list.save
      flash[:notice] = "List successfully created!🎉"
      redirect_to user_path(current_user.id)
    else 
      flash[:alert] = "Uh oh! Something went wrong, please try again later 😔"
      render :new
    end 
  end 

  def edit 
    @list = List.find(params[:id])
  end 

  def update 
    @list = List.find(params[:id])

    # remove everything in the current list
    @list.types.each do |type|
      type.destroy
    end 

    # rebuild everything
    if @list.update(list_params)
      flash[:notice] = "List successfully updated!🎉"
      redirect_to list_path(@list)
    else 
      render :edit
    end 
  end 

  def show # individual List pages
    @list = List.find(params[:id])

    if @list.collector != nil # if the list is being collected
      # we find the name and display it
      @assigned = User.find(@list.collector).username
    end 
  end

  def assign # the collector has clicked to assign this task to themselves
    list = List.find(params[:id])
    list.collector = current_user.id
    list.update(status: 1) # 0 - unfulfilled, 1 - doing, 2 - done
    if list.save 
      flash[:notice] = "List successfully assigned!🎉"
      redirect_to user_path(current_user.id)
    else 
      flash[:alert] = "Uh oh! Something went wrong, please try again later 😔"
    end
  end 

  def complete
    list = List.find(params[:id])
    list.update(status: 2) 
    if list.save 
      flash[:notice] = "Thank you for saving Mother Earth! You deserve a trophy!🏆"
      redirect_to user_path(current_user.id)
    end 
  end 

  def destroy 
    # delete all dependencies
    List.find(params[:id]).types.each do |type|
      type.destroy
    end 

    # delete the lists
    if List.find(params[:id]).destroy
      flash[:notice] = "List successfully deleted."
      redirect_to user_path(current_user.id)
    else 
      flash[:alert] = "Uh oh! Something went wrong, please try again later 😔"
    end 
  end 

  private
  
  def list_params
    params.require(:list).permit(:address, :pickUpDate, :remarks, :timeslot ,types_attributes: [:material, :remarks, :weight])
  end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<% if @list.errors.any? %>
    <%= pluralize(@list.errors.count, "error") %>
    <% @list.errors.full_messages.each do |err| %>
        <div> 
            <%= err %>
        </div>
    <% end %>
<% end %>

<div class="container list-form" >
<%= form_for @list do |f| %>
    <div>
        <%= f.label :address %>
        <%= f.text_field :address %>
    </div>

    <div>
        <%= f.label :pickUpDate %>
        <%= f.date_field :pickUpDate %>
    </div>

    <div>
        <%= f.label :timeslot %>
        <%= f.time_field :timeslot  %>
    </div>

    <div>
        <%= f.label :remarks %>
        <%= f.text_field :remarks %>
    </div>

    <hr>
    <h3>Items</h3>

    <button class="btn btn-outline-secondary mb-3" id="addItemToList"> Add new item</button>

    <% if @list.types.length != 0 %>
    <%# If this is an edit list %>
        <% @list.types.each do |type| %>
            <%= content_tag :div, class: "TypesContainer", data: { types: type } do %>
            <% end %>
        <% end %>
    <% else %>
        <div class="TypesContainer"></div>
    <% end %>

    <div id="submitBtn"><%= f.submit class: 'btn btn-outline-success'%></div>

    <%= javascript_pack_tag 'addTypeToList' %>
<% end %>
</div>

app/views/lists/_list_summary.html.erb
<% @lists.in_groups_of(4, false).each do |group| %>
     <div class="row mb-2">
     <% group.each do |list| %>

    <div class="col-md-3 col-md-offset-2 p-3 mt-1">
        <div class="card card-m">
            <div class="card-body">
            <% if list.status === 0 %>
                <p class="badge badge-op">Open</p>
            <% elsif list.status === 1 %>
                <p class="badge badge-inf">Assigned</p>
            <% else %>
                <p class="badge badge-scs">Completed</p>
            <% end %>

            <p><strong><%= list.address %></strong><p>
            <div class="mx-auto card-text">
                <span><em>Posted on:<br> <%= time_tag(list.created_at) %></em></span><br>
                <span><%= list.travel_distance %> away from you</span><br>
                <% if current_user.role === "user" %>
                    <span>Approximately: <%= list.travel_time %></span>
                <% end %>
                <% sum = 0 %>
                <% list.types.each do |ele| %>
                    <% sum = sum + ele.weight %>
                <% end %>
                <span>Weight: <%= sum %> kg</span>
                <span style="display: block; margin: auto; width: fit-content;">
                <%= link_to "Show more", list_path(list), :class => 'mx-auto btn btn-outline-info my-3' %>
                </span>
            </div>
        </div>
        </div>
    </div>
<% end %> 
</div>
<% end %>

<%= javascript_tag do %>
    $(function() {
        $("time.timeago").timeago();
    });
<% end %>

app/views/lists/edit.html.erb
<div class="container  mb-3">
<h1>Edit your list</h1>
</div>
<br>
<%= render "lists/form" %>

app/views/lists/index.html.erb
<%= render "lists/list_summary" %> 

app/views/lists/new.html.erb
<div class="container mb-3 list-form">
    <h1>New List</h1>
</div>
<%= render "lists/form" %>

app/views/lists/show.html.erb
<div class="container">
<h1>Lists</h1>
<hr>
<p><%= render_shareable %></p>
<p>Belongs to: 
    <%= link_to user_path(@list.user) do %>
    <span class="badge pill badge-user mr-3">
        <%= @list.user.username %>
        </span>
    <% end %>
    <%if current_user.role=="user"%>
    <%= link_to "chat", rooms_show_path(:target_user_id => @list.user.id) %>
    <%end%>

</p>
<p>Pick up address: <%= @list.address %></p>
<p>Pick up date: <%= @list.pickUpDate.to_s %></p>
<% if @list.timeslot != nil %>
    <p>Pick up time: <%= @list.timeslot.strftime('%H:%M %p') %></p>
<% end %>
<p>Created at: <%= @list.created_at.to_date %>, <%= time_ago_in_words(@list.created_at) %> ago</p>
<p>Remarks: <%= @list.remarks %></p>
<% if @list.status === 0 %>
    <p>Status: Open</p>
<% elsif @list.status === 1 %>
    <p>Status: Assigned</p>
<% else %>
    <p>Status: Completed</p>
<% end %>


<% sum = 0 %>
<% @list.types.each do |type| %>
    <% sum = sum + type.weight %>
<% end %>
<p>Total weight: <%= sum %>KG</p>

<hr>

<h3>Items in this list </h3>

<table class="table table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">No.</th>
      <th scope="col">Material</th>
      <th scope="col">Remarks</th>
      <th scope="col">Weight (KG)</th>
    </tr>
  </thead>
  <tbody>
    <% @list.types.each_with_index do |type, idx|%>
        <tr class="table-primary">
            <th scope="row"><%= idx + 1 %></th>
            <td><%= type.material %></td>
            <td><%= type.remarks %></td>
            <td><%= type.weight %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<hr>

<h3>Status</h3>
<p>
    <% if @list.status == 0 %>
        This list is open
    <% elsif @list.status == 1 %>
        Accepted by: 
        <%= link_to user_path(@list.collector) do %>
            <%= @assigned %>
        <% end %>
            <%if current_user.role=="recycler"%>
    <%= link_to "chat", rooms_show_path(:target_user_id => @list.collector) %>
    <%end%>

    <% elsif @list.status == 2 %>
        Completed by: 
        <%= link_to user_path(@list.collector) do %>
            <%= @assigned %>
        <% end %>
    <% end %>
</p>

<%# The user is either admin or collecter and the status is open #%>
<%  if (current_user.role === "user" || current_user.role === "admin") && (@list.status === 0)  %>
    <%= form_for @list, url: assign_list_path(@list.id) do |f| %>
        <%= f.submit "Accept" ,:class => 'btn btn-outline-info btn-lg'%>
    <% end %>
<% end %>

<%# Admin/ assigned collector %>
<% if @list.user.id === current_user.id || current_user.role === "admin" || @list.collector === current_user.id %>
    <p>Belongs to you</p> <%# For now.. We display the same message for all %>

    <%# This list belongs to the collector and the list is in progress %>
    <% if current_user.role === "user" && @list.status === 1 %>
        <%= form_for @list, url: complete_list_path(@list.id) do |f| %>
            <%= f.submit "Complete" ,:class => 'btn btn-outline-success btn-lg'%>
        <% end %>
    <% end %>
<% end %>

<%# The user can edit and destroy their own lists #%>
    
<%# Owner can delete list if it is open or completed i.e. not assigned %>
<% if current_user.id === @list.user.id && (@list.status === 0 || @list.status === 2) || current_user.role === "admin" %>
    <%= link_to "Delete", list_path(@list), method: "delete", data:{ confirm: "Are you sure?"},:class => 'btn btn-outline-danger' %>
<% end %>   

<%# Owner can only edit when the list is open or assigned i.e. not completed %>
<% if current_user.id === @list.user.id && (@list.status === 0) || current_user.role === "admin" %>
    <%= link_to "Edit", edit_list_path(@list) ,:class => 'btn btn-outline-info'%>
<% end %>

</div>