config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  get 'intro/index'
  get 'intro/show'
  devise_for :users
  
  resources :lists # /list/index 
  get "users/:id/index", to: "users#index", as: :home #user/index => page that shows all lists
  get "users/:id", to: "users#show", as: :user # user/show
  
  # for fufillment
  patch "/list/:id/assign", to: "lists#assign", as: :assign_list
  patch "/list/:id/complete", to: "lists#complete", as: :complete_list

  # for admin actions
  patch "/users/:id/role", to: "users#updateRole"
  
 resources :types
  
  root 'intro#index'

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_type, only: [:show, :edit, :destroy, :update]

  def index
    @types = Type.all
  end

  def create
    #@list = List.find(params[:list_id])
    #@type = @list.types.build(type_params)
    @type = Type.new(type_params)
    if @type.save
      redirect_to types_path
    else
      render :new
    end
  end

  def new
    @type = Type.new
  end

  def show
  end

  def destroy
    if @type.destroy
      redirect_to types_path
    else
      render :index
    end
  end

  def update
    #list = List.find(params[:list_id])
    if @type.update(type_params)
      redirect_to type_path
    else
      render :edit
    end
  end

  def edit
    #@list = List.find(params[:list_id])
  end

  private

  def set_type
    @type = Type.find(params[:id])
  end

  def type_params
    params.require(:type).permit(:material, :remarks, :weight)
  end

end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_for @type do |f| %>

<div>
    <h3>Materials</h3>
    <%= f.radio_button :material, :value => "Metal", :checked => true %>
    <%= f.label :material, "Metal" %>
    <%= f.radio_button :material, :value => "Glass", :checked => true %>
    <%= f.label :material, "Glass" %>
    <%= f.radio_button :material, :value => "Plastic", :checked => true %>
    <%= f.label :material, "Plastic" %>
</div>
<div>
    <%= f.label :remarks, "Remarks" %>
    <%= f.text_field :remarks %>
</div>
<div>
    <%= f.label :weight, "Weight(KG)" %>
    <%= f.number_field :weight, in: 0.1..10, step: 0.1 %>
</div>

<%= f.submit "Submit" %>
<% end %>

app/views/types/edit.html.erb
<h1>Types#edit</h1>
<p>Find me in app/views/types/edit.html.erb</p>

<%= render  "types/form" %>

app/views/types/index.html.erb
<h1>Types#index</h1>
<p>Find me in app/views/types/index.html.erb</p>

<%= link_to "Add Types", new_type_path %>
<table class="table mt-4">
<tr>
    <td>Edit</td>
    <td>Material</td>
    <td>Remarks</td>
    <td>Weight</td>
    <td>Updated Date</td>
</tr>

<% @types.each do |type| %>
<tr>
    <td><%= link_to type.id, edit_type_path(type.id) %></td>
    <td><%= type.material.split('"')[1] %></td>
    <td><%= type.remarks %></td>
    <td><%= type.weight %>kg</td>
    <td><%= type.updated_at_was.strftime("%Y-%m-%d")%></td>
</tr>

<% end %>

</table>

app/views/types/new.html.erb
<h1>Types#new</h1>
<p>Find me in app/views/types/new.html.erb</p>

<%= render  "types/form" %>

app/views/types/show.html.erb
<h1>Types#show</h1>
<p>Find me in app/views/types/show.html.erb</p>


        <div>
            <h3>Material: <%= @type.material.split('"')[1] %></h3>
            <h3>Remarks: <%= @type.remarks %></h3>
            <h3>Weight: <%= @type.weight %>kg</h3>
        </div>