config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  get 'intro/index'
  get 'intro/show'
  devise_for :users
  
  resources :lists # /list/index 
  get "users/:id/index", to: "users#index", as: :home #user/index => page that shows all lists
  get "users/:id", to: "users#show", as: :user # user/show
  
  # for fufillment
  patch "/list/:id/assign", to: "lists#assign", as: :assign_list
  patch "/list/:id/complete", to: "lists#complete", as: :complete_list

  # for admin actions
  patch "/users/:id/role", to: "users#updateRole"
  
 resources :types
  
  root 'intro#index'

end

app/models/user.rb
class User < ApplicationRecord
  geocoded_by :address
  after_validation :geocode

  validates :address, :presence => true,
    :length => { :minimum => 5 }

  validates :phone_number, format: { with: /(6|8|9)\d{7}/, message: "should be valid" }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:user, :recycler, :admin] # collector = user
  after_initialize :set_default_role, :if => :new_record?

  has_many :lists
  has_one_attached :user_image
  has_many :messages
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/users_controller.rb
require 'net/http'
require "uri"

class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :set_user, only: [:index]
  def index # landing page when users login, => shows all the lists
    if (current_user.role === "user") # user is a collector

      # show lists with accordance to distance whereby status is either open or assigned i.e. not completed
      @lists = List.near(current_user.address, 999999, order: 'distance', units: :km).where("STATUS=0")

      # for each list, we add new attributes of distance travelled and traveling time
      @lists.each do |li|
        details = get_travel_time(li.latitude, li.longitude)
        li.travel_distance = details["distance"]["text"]
        li.travel_time = details["duration"]["text"]
      end
    else # user is recycler or admin
      @lists = List.near(current_user.address, 999999, order: 'distance', units: :km)

      @lists.each do |li|
        details = get_travel_time(li.latitude, li.longitude)
        li.travel_distance = details["distance"]["text"]
      end 
    end
  end

  def show # show user's dashboards
    @user = User.find(params[:id])

    # initialise
    lists = Array.new
    @in_progress = Array.new
    @completed = Array.new

    # if the user is a collector
    if @user.role === "user"
      # find all the Lists where the user is a collector
      lists = List.where(collector: @user.id)
    elsif @user.role === "recycler"
      lists = User.find(@user.id).lists
    else # this person is an admin, just display everything
      lists = List.all
      @users = User.all
    end 

    # we filter the lists to completed and in_progress
    lists.each do |list|
      if list.status === 1 || list.status === 0 then @in_progress << list
      else @completed << list
      end 

    end 

    @messages = Message.all
    

  end 

  def new
  end

  def create
  end

  def destroy
  end

  def updateRole
    user = User.find(params[:id])
    user.role = params[:role]
    user.save

  end

  private
  
  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:fname, :lname, :desc, :username, :password,:email, :phone, :address, :city, :country)
  end

  # @params: destination lat and lng
  def get_travel_time(lat, lng)
    uri = URI.parse("https://maps.googleapis.com/maps/api/distancematrix/json?origins=#{current_user.latitude},#{current_user.longitude}&destinations=#{lat},#{lng}&key=#{ENV['GOOGLE_API_KEY']}")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    req = Net::HTTP::Get.new(uri.request_uri)
    response = http.request(req)
    return JSON.parse(response.body)["rows"][0]["elements"][0]
  end 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_carousel.html.erb
<div class="container">
    <h3 class="mb-3"><%= title %> (<%= lists.length%>)</h3>
    <% if lists.length > 0 %>
    <div class="glide">
      <div class="glide__track" data-glide-el="track">
        <ul class="glide__slides">
          <% lists.each do |li| %>
            <li class="glide__slide card card-d">
                <div class="card-body" style="width:200px">
                    <% if li.status === 0 %>
                        <span class="badge pill badge-op">Open</span>
                    <% elsif li.status === 1 %>
                        <span class="badge badge-inf">Assigned</span>
                    <% else %>
                        <span class="badge badge-scs">Completed</span>
                    <% end %>
                    <p class="pt-3">Pickup #100<%= li.id %></p>
                    <%= link_to "Show more", list_path(li), :class => 'btn btn-outline-info mb-3' %>
                </div>
            </li>
            <% end %>
        </ul>
      </div>
        <div class="glide__arrows" data-glide-el="controls">
            <button class="glide__arrow glide__arrow--right" data-glide-dir=">" style="font-size:18px;">></button>
        </div>
    </div>
    <% end %>
</div>
<script src="https://cdn.jsdelivr.net/npm/@glidejs/glide"></script>
<script>
    var sliders = document.querySelectorAll('.glide');
        for (var i = 0; i < sliders.length; i++) {
        var glide = new Glide(sliders[i], {
            type: 'slider',
            startAt: 0,
            perView: 3,
            breakpoints: {
                1024: { perView: 2 },
                700: { perView: 1 }
            }
        });
        glide.mount();
        }
</script>

app/views/users/_lists_display.html.erb
<h3><%= title %> (<%= lists.length%>)</h3>

<div>
    <% lists.each do |li| %>
        <div>
            <p>Pick up address: <%= li.address %></p>
            <%= link_to "Show more", list_path(li), :class => 'btn btn-outline-info mb-3' %>
            <hr>
        </div>
    <% end %>
</div>

app/views/users/_users_display.html.erb
<% users.each do |u| %>

<div>
    <div>Username: <%= u.username %></div>
    <div>Role: <%= u.role %></div>
    <div class="mt-1 mb-1"> Change role
    </div>
        <button class="btn btn-outline-primary" data-userid="<%= u.id %>" data-role="recycler" onclick="changeRole(this)"> Recycler </button>
        <button class="btn btn-outline-primary" data-userid="<%= u.id %>" data-role="user" onclick="changeRole(this)"> User </button>
        <button class="btn btn-outline-primary" data-userid="<%= u.id %>" data-role="admin" onclick="changeRole(this)"> Admin </button>
</div>
<hr>
<% end %>

<script type="text/javascript">
  const changeRole =(e)=>{ 
    fetch(`/users/${e.getAttribute("data-userid")}/role`,{
        method: "PATCH",
            headers: {
    'X-CSRF-Token' :document.head.querySelector('meta[name="csrf-token"]').content,
    'Content-Type': 'application/json'
    },
        body: JSON.stringify({role:e.getAttribute("data-role")})
    })
  }
</script>

app/views/users/index.html.erb
<div class="container mt-3">

<%# Scripts for Google Maps to run #%>
<script src="//maps.google.com/maps/api/js?key=AIzaSyD5o3njhXcn3a6DDyBgWKQtxvZTfDorw1k"></script>  
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>  
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
<script src='//underscorejs.org/underscore-min.js' type='text/javascript'></script>
<script src='//cdn.jsdelivr.net/gmaps4rails/2.1.2/gmaps4rails.js'> </script>
<script src='//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js'> </script>
<%# End scripts for Google Maps #%>

<% if current_user.role === "user"%>
<h1 class="text-center">Browse Lists</h1>
<% else %>
<h1 class="text-center">See what others are recycling</h1>
<% end %>

<div class="row mx-auto justify-content-center">
<% if current_user.role != "user" %>
    <%= link_to "Create new list", new_list_path , :class => 'btn btn-outline-success mt-3 mb-2'%>
<% end %>
</div>

<%= content_tag :div, class: "lists", data: { lists: @lists } do %>
<% end %>


  <div class="row">
        <div class="mx-auto mt-4 mb-5 listmap" id="map" style='width: 1100px; height: 300px;'></div>  
  </div>

 <div class="col">
<%= render "lists/list_summary" %> 

<% if @lists.length === 0 %>
    <p>There are no lists.</p>
<% end %>

<%= javascript_pack_tag 'map' %>

</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container dashboard">
<h1 style="text-transform:capitalize;" class="mb-5">Hello, <em><%= current_user.username %></em></h1>

 <div class="row">
    <div class="col-md-3 profile text-center">
        <% if @user.user_image.attached? %>
            <%= image_tag @user.user_image , width: "150px", height: "150px" %>
        <% else %>
     <%= image_tag('/profile_pic.jpg', width: "150px", height: "150px") %>
        <% end %>

        <p class="mt-3"> Username: <%= @user.username %></p>
        <% if current_user.role != "user" %>
            <%= link_to "Explore", home_path(current_user.id) , :class => 'btn btn-outline-info' %>
            <%= link_to "Create new list", new_list_path , :class => 'btn btn-outline-success'%>
        <% end %>

        <% if current_user.role != "recycler" && current_user.role != "admin" %>
            <%= link_to "Browse lists", home_path(current_user.id) , :class => 'btn btn-outline-info' %>
        <% end %>
    </div>

<% if current_user.role != "admin" %>
<div class="col-8 ml-5">
<div class="my-2">
<%= render partial: 'carousel', locals:  {title: "In-progress", lists:@in_progress} %>
</div>
<div class="my-2">
<%= render partial: 'carousel', locals:  {title: "Completed Lists", lists:@completed} %>
</div>
 <%#= render partial: 'lists_display', locals: {title: "Existing lists/ inprogress", lists:@in_progress} %>
 <%#= render partial: 'lists_display', locals: {title: "Completed lists", lists:@completed} %>
</div>
<% else %>
<div class="col-4">
<a class="button default ok" href="#users-information" data-toggle="collapse" aria-expanded="false">
   <h2>
       View Users   
   </h2>
</a>
<div id="users-information" class="collapse">
 <%= render partial: 'users_display', locals: {users:@users} %>
</div>
</div>

<div class="col-5">
<a class="button default ok" href="#lists-information" data-toggle="collapse" aria-expanded="false">
   <h2>
       View Lists   
   </h2>
</a>
<div id="lists-information" class="collapse">
 <%= render partial: 'lists_display', locals: {title: "Existing lists/ inprogress", lists:@in_progress} %>
 <%= render partial: 'lists_display', locals: {title: "Completed lists", lists:@completed} %>
</div>
</div>
 <% end %>

</div>
</div>