config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  get 'intro/index'
  get 'intro/show'
  devise_for :users
  
  resources :lists # /list/index 
  get "users/:id/index", to: "users#index", as: :home #user/index => page that shows all lists
  get "users/:id", to: "users#show", as: :user # user/show
  
  # for fufillment
  patch "/list/:id/assign", to: "lists#assign", as: :assign_list
  patch "/list/:id/complete", to: "lists#complete", as: :complete_list

  # for admin actions
  patch "/users/:id/role", to: "users#updateRole"
  
 resources :types
  
  root 'intro#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trashtalks | Connect with a nearby recycling agent today</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Arbutus+Slab&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,600;0,700;1,600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    </head>

  <body>
    <% if notice %>
      <p class="alert alert-success notice mb-0"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger mb-0"><%= alert %></p>
    <% end %>
    <div class="navbar top-bar">
        <div><%= link_to "#Trashtalks", root_path, class: "brand ml-2" %></div>
        <a href="https://github.com/yh-sg/trashtalks" target="blank"><i class="fa fa-github git mr-2" style="font-size: 24px;"></i></a>
    </div>

    <% if user_signed_in? %>
    <div class="d-flex flex-row-reverse mt-4 mr-5">
      <div class="dropdown show">
        <% if current_user.role == "user"%>
        <a class="dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Collector
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
          <%= link_to "Dashboard", user_path(current_user.id), class: "dropdown-item" %>
          <%= link_to "Browse lists", home_path(current_user.id), class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to  "Logout", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
        </div>
        <% elsif current_user.role == "recycler"%>
        <a class="dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="text-transform:capitalize;">
          <%= current_user.role %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
          <%= link_to "Dashboard", user_path(current_user.id), class: "dropdown-item" %>
          <%= link_to "How It Works", intro_show_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to  "Logout", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
        </div>
        <% elsif current_user.role == "admin"%>
        <a class="dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="text-transform:capitalize;">
          <%= current_user.role %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
          <%= link_to  "Logout", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
        </div>
        <% end %>
      </div>
      <span class="badge pill badge-user mr-3">
        <%= current_user.username %>
      </span>
        <% else %>
        <div class="navbar second-nav">
          <ul class="breadcrumb second-bread mx-auto">
            <li><%= link_to "Log In", new_user_session_path, class: "bread-item mr-4" %></li>
            <span class="mr-4">|</span>
            <%= link_to "How It Works", intro_show_path, class: "bread-item" %>
          </ul>
        </div>
      <% end %>
    </div>
    <!-- <li><%= link_to "Sign Up", new_user_registration_path, class: "bread-item mr-4" %></li>
        <span class="mr-4">|</span> -->
    <%= yield %>
    <footer>
      <div class="container footer">
        <div class="row justify-content-md-center">
          <div class="col-sm-3 text-center my-2">
            &copy; <strong>YAME</strong> 2020.<br>
            All Rights Reserved.
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>